/**
 * Dashboard Store
 *
 * Bridge between HardwareView and TopBar (UI consumer).
 * statusCounts are computed from espStore via getESPStatus (reactive).
 * TopBar reads counts/breadcrumb and writes filter changes.
 *
 * Extended with Custom Dashboard Layout management (Phase 2).
 * Phase 3: Server-API sync (POST/PUT/DELETE) with localStorage as cache.
 */

import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import { useEspStore } from '@/stores/esp'
import { getESPStatus } from '@/composables/useESPStatus'
import { dashboardsApi, type DashboardDTO } from '@/api/dashboards'
import { SENSOR_TYPE_CONFIG, type SensorCategoryId } from '@/utils/sensorDefaults'
import { createLogger } from '@/utils/logger'

const logger = createLogger('DashboardStore')

export type StatusFilter = 'online' | 'offline' | 'warning' | 'safemode'
export type TypeFilter = 'all' | 'mock' | 'real'

/** Widget type identifiers */
export type WidgetType = 'line-chart' | 'gauge' | 'sensor-card' |
  'historical' | 'actuator-card' | 'actuator-runtime' |
  'esp-health' | 'alarm-list' | 'multi-sensor'

/** Single widget configuration */
export interface DashboardWidget {
  id: string
  type: WidgetType
  x: number
  y: number
  w: number
  h: number
  config: {
    sensorId?: string
    actuatorId?: string
    espId?: string
    gpio?: number
    sensorType?: string
    zoneId?: string
    timeRange?: '1h' | '6h' | '24h' | '7d' | 'custom'
    showThresholds?: boolean
    title?: string
    color?: string
    syncTimeAxis?: boolean
    /** Comma-separated sensor IDs for multi-sensor widget */
    dataSources?: string
    /** Explicit Y-axis min override */
    yMin?: number
    /** Explicit Y-axis max override */
    yMax?: number
    /** Zone filter for alarm-list, esp-health, actuator-runtime (zone_id or null = all zones) */
    zoneFilter?: string | null
  }
}

/** Dashboard scope */
export type DashboardScope = 'zone' | 'cross-zone' | 'sensor-detail'

/** Display target configuration — where and how a dashboard is rendered */
export interface DashboardTarget {
  view: 'monitor' | 'hardware'
  placement: 'page' | 'inline' | 'side-panel' | 'bottom-panel'
  anchor?: string
  panelPosition?: 'left' | 'right'
  panelWidth?: number
  order?: number
}

/** Dashboard layout */
export interface DashboardLayout {
  id: string
  /** Server UUID — set after first successful API sync */
  serverId?: string
  name: string
  description?: string
  createdAt: string
  updatedAt: string
  widgets: DashboardWidget[]
  scope?: DashboardScope
  zoneId?: string
  autoGenerated?: boolean
  sensorId?: string
  target?: DashboardTarget
}

export const useDashboardStore = defineStore('dashboard', () => {
  const espStore = useEspStore()

  /* ── Visibility ── */
  const showControls = ref(false)

  /* ── Counts (computed from espStore via getESPStatus — reactive to device changes) ── */
  const statusCounts = computed(() => {
    let online = 0, offline = 0, warning = 0, safeMode = 0
    for (const device of espStore.devices) {
      const status = getESPStatus(device)
      switch (status) {
        case 'online':
        case 'stale':
          online++
          break
        case 'offline':
        case 'unknown':
          offline++
          break
        case 'error':
          warning++
          break
        case 'safemode':
          safeMode++
          break
      }
    }
    return { online, offline, warning, safeMode }
  })

  /* ── Device counts (computed from espStore — reactive to device changes) ── */
  const deviceCounts = computed(() => ({
    all: espStore.devices.length,
    mock: espStore.mockDevices.length,
    real: espStore.realDevices.length,
  }))
  const pendingCount = computed(() => espStore.pendingCount)

  /* ── Filters (bidirectional: TopBar writes, DashboardView reads) ── */
  const activeStatusFilters = ref<Set<StatusFilter>>(new Set())
  const filterType = ref<TypeFilter>('all')

  /* ── Breadcrumb (written by Views, read by TopBar) ── */
  const breadcrumb = ref<{
    level: 1 | 2 | 3
    zoneName: string
    deviceName: string
    sensorName: string
    ruleName: string
    dashboardName: string
  }>({
    level: 1,
    zoneName: '',
    deviceName: '',
    sensorName: '',
    ruleName: '',
    dashboardName: '',
  })

  /* ── Modal/Panel triggers (TopBar writes, DashboardView reads) ── */
  const showCreateMock = ref(false)
  const showPendingPanel = ref(false)

  /* ── Navigation request (TopBar → DashboardView) ── */
  const navRequestCount = ref(0)
  const navTarget = ref<1 | 2 | 3>(1)

  /* ── Computed ── */
  const hasProblems = computed(() =>
    statusCounts.value.warning > 0 || statusCounts.value.safeMode > 0
  )

  const problemMessage = computed(() => {
    const { warning, safeMode, offline, online } = statusCounts.value
    if (warning > 0) return `${warning} Gerät(e) mit Fehlern`
    if (safeMode > 0) return `${safeMode} Gerät(e) im Safe-Mode`
    if (offline > 0 && online > 0) return `${offline} Gerät(e) offline`
    return ''
  })

  const hasPendingDevices = computed(() => pendingCount.value > 0)

  /* ── Actions ── */
  function toggleStatusFilter(filter: StatusFilter) {
    const next = new Set(activeStatusFilters.value)
    if (next.has(filter)) next.delete(filter)
    else next.add(filter)
    activeStatusFilters.value = next
  }

  function resetFilters() {
    filterType.value = 'all'
    activeStatusFilters.value = new Set()
  }

  function activate() {
    showControls.value = true
  }

  function deactivate() {
    showControls.value = false
    resetFilters()
  }

  function requestNavigate(level: 1 | 2 | 3) {
    navTarget.value = level
    navRequestCount.value++
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // CUSTOM DASHBOARD LAYOUTS (Phase 2)
  // ═══════════════════════════════════════════════════════════════════════════

  const STORAGE_KEY = 'automation-one-dashboard-layouts'

  /** All saved layouts */
  const layouts = ref<DashboardLayout[]>([])
  /** Currently active layout ID */
  const activeLayoutId = ref<string | null>(null)
  /** Server sync in progress */
  const isSyncing = ref(false)
  /** Last server sync error message (null = no error) */
  const lastSyncError = ref<string | null>(null)

  /** Currently active layout */
  const activeLayout = computed<DashboardLayout | null>(() =>
    layouts.value.find(l => l.id === activeLayoutId.value) ?? null
  )

  /** Lookup layout by local ID or server UUID (for deep-link robustness) */
  function getLayoutById(id: string): DashboardLayout | undefined {
    return layouts.value.find(l => l.id === id || l.serverId === id)
  }

  /** Load layouts from localStorage */
  function loadLayouts() {
    try {
      const stored = localStorage.getItem(STORAGE_KEY)
      if (stored) {
        layouts.value = JSON.parse(stored)
        if (layouts.value.length > 0 && !activeLayoutId.value) {
          activeLayoutId.value = layouts.value[0].id
        }
      }
    } catch {
      layouts.value = []
    }
  }

  /** Persist layouts to localStorage */
  function persistLayouts() {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(layouts.value))
    } catch {
      // localStorage full or unavailable
    }
  }

  /** Create a new dashboard layout */
  function createLayout(name: string, description?: string): DashboardLayout {
    const layout: DashboardLayout = {
      id: `dash-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      name,
      description,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      widgets: [],
    }
    layouts.value.push(layout)
    activeLayoutId.value = layout.id
    persistLayouts()
    syncLayoutToServer(layout.id)
    return layout
  }

  /** Save current layout widgets */
  function saveLayout(layoutId: string, widgets: DashboardWidget[]) {
    const idx = layouts.value.findIndex(l => l.id === layoutId)
    if (idx === -1) return
    layouts.value[idx] = {
      ...layouts.value[idx],
      widgets,
      updatedAt: new Date().toISOString(),
    }
    persistLayouts()
    syncLayoutToServer(layoutId)
  }

  /** Delete a layout */
  function deleteLayout(layoutId: string) {
    const layout = layouts.value.find(l => l.id === layoutId)
    const serverId = layout?.serverId
    layouts.value = layouts.value.filter(l => l.id !== layoutId)
    if (activeLayoutId.value === layoutId) {
      activeLayoutId.value = layouts.value[0]?.id ?? null
    }
    persistLayouts()
    if (serverId) deleteLayoutFromServer(serverId)
  }

  /** Export layout as JSON string (ensures description is always present) */
  function exportLayout(layoutId: string): string | null {
    const layout = layouts.value.find(l => l.id === layoutId)
    if (!layout) return null
    return JSON.stringify({ ...layout, description: layout.description || '' }, null, 2)
  }

  /** Import layout from JSON string */
  function importLayout(json: string): DashboardLayout | null {
    try {
      const layout = JSON.parse(json) as DashboardLayout
      layout.id = `dash-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
      layout.serverId = undefined
      layout.createdAt = new Date().toISOString()
      layout.updatedAt = new Date().toISOString()
      layouts.value.push(layout)
      persistLayouts()
      syncLayoutToServer(layout.id)
      return layout
    } catch {
      return null
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // SERVER API SYNC (Phase 3)
  // ═══════════════════════════════════════════════════════════════════════════

  /** Convert server DTO to local DashboardLayout */
  function serverToLocal(dto: DashboardDTO): DashboardLayout {
    return {
      id: dto.id,
      serverId: dto.id,
      name: dto.name,
      description: dto.description || undefined,
      createdAt: dto.created_at || new Date().toISOString(),
      updatedAt: dto.updated_at || new Date().toISOString(),
      widgets: (dto.widgets || []).map(w => ({
        id: w.id,
        type: w.type as WidgetType,
        x: w.x,
        y: w.y,
        w: w.w,
        h: w.h,
        config: (w.config || {}) as DashboardWidget['config'],
      })),
      scope: dto.scope as DashboardScope | undefined,
      zoneId: dto.zone_id || undefined,
      autoGenerated: dto.auto_generated || undefined,
      sensorId: dto.sensor_id || undefined,
      target: (dto.target as unknown) as DashboardTarget | undefined,
    }
  }

  /**
   * Fetch dashboards from server API and merge with localStorage cache.
   * Server dashboards take priority (matched by serverId).
   * Called on store init and editor mount.
   */
  async function fetchLayouts(): Promise<void> {
    isSyncing.value = true
    lastSyncError.value = null
    try {
      const response = await dashboardsApi.list()
      if (response.success && response.data.length > 0) {
        const serverLayouts = response.data.map(serverToLocal)

        // Merge: server layouts replace local ones with same serverId
        const serverIds = new Set(serverLayouts.map(l => l.serverId))
        const localOnly = layouts.value.filter(l => !l.serverId || !serverIds.has(l.serverId))

        layouts.value = [...serverLayouts, ...localOnly]
        persistLayouts()

        logger.info(`Fetched ${serverLayouts.length} dashboards from server, ${localOnly.length} local-only`)

        // Proactive orphan sync: push local-only dashboards to server
        const orphans = localOnly.filter(l => !l.serverId)
        if (orphans.length > 0) {
          logger.info(`Syncing ${orphans.length} orphan dashboard(s) to server`)
          for (const orphan of orphans) {
            syncLayoutToServer(orphan.id)
          }
        }
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e)
      lastSyncError.value = msg
      logger.warn('Failed to fetch dashboards from server, using localStorage cache:', msg)
    } finally {
      isSyncing.value = false
    }
  }

  /** Per-layout debounce timers (prevents losing edits when switching dashboards) */
  const _saveDebounceTimers = new Map<string, ReturnType<typeof setTimeout>>()
  const SAVE_DEBOUNCE_MS = 2000

  /** Sync layout to server (fire-and-forget, debounced per layout) */
  function syncLayoutToServer(layoutId: string): void {
    const existing = _saveDebounceTimers.get(layoutId)
    if (existing) clearTimeout(existing)

    const timer = setTimeout(async () => {
      _saveDebounceTimers.delete(layoutId)
      const layout = layouts.value.find(l => l.id === layoutId)
      if (!layout) return

      const payload = {
        name: layout.name,
        description: layout.description || '',
        widgets: layout.widgets.map(w => ({
          id: w.id,
          type: w.type,
          x: w.x,
          y: w.y,
          w: w.w,
          h: w.h,
          config: w.config || {},
        })),
        scope: layout.scope,
        zone_id: layout.zoneId,
        auto_generated: layout.autoGenerated || false,
        sensor_id: layout.sensorId,
        target: layout.target || null,
      }

      try {
        if (layout.serverId) {
          // Update existing server dashboard
          await dashboardsApi.update(layout.serverId, payload)
          logger.debug(`Synced layout "${layout.name}" to server (update)`)
        } else {
          // Create new server dashboard
          const response = await dashboardsApi.create(payload)
          if (response.success && response.data) {
            // Store server UUID for future updates
            const idx = layouts.value.findIndex(l => l.id === layoutId)
            if (idx !== -1) {
              layouts.value[idx] = { ...layouts.value[idx], serverId: response.data.id }
              persistLayouts()
            }
            logger.debug(`Synced layout "${layout.name}" to server (create, serverId=${response.data.id})`)
          }
        }
        lastSyncError.value = null
      } catch (e) {
        const msg = e instanceof Error ? e.message : 'Layout konnte nicht gespeichert werden'
        lastSyncError.value = msg
        logger.warn(`Failed to sync layout "${layout.name}" to server`, e)
      }
    }, SAVE_DEBOUNCE_MS)
    _saveDebounceTimers.set(layoutId, timer)
  }

  /** Delete layout from server (fire-and-forget) */
  async function deleteLayoutFromServer(serverId: string): Promise<void> {
    try {
      await dashboardsApi.delete(serverId)
      logger.debug(`Deleted layout from server (serverId=${serverId})`)
    } catch (e) {
      logger.warn(`Failed to delete layout from server (serverId=${serverId})`, e)
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // DASHBOARD TEMPLATES
  // ═══════════════════════════════════════════════════════════════════════════

  /** Pre-defined dashboard templates */
  const DASHBOARD_TEMPLATES: Record<string, { name: string; description: string; widgets: Omit<DashboardWidget, 'id'>[] }> = {
    'zone-overview': {
      name: 'Zonen-Übersicht',
      description: '4 Gauges für Temperatur, Luftfeuchtigkeit, pH und EC',
      widgets: [
        { type: 'gauge', x: 0, y: 0, w: 3, h: 3, config: { title: 'Temperatur', sensorType: 'temperature' } },
        { type: 'gauge', x: 3, y: 0, w: 3, h: 3, config: { title: 'Luftfeuchtigkeit', sensorType: 'humidity' } },
        { type: 'gauge', x: 6, y: 0, w: 3, h: 3, config: { title: 'pH-Wert', sensorType: 'ph' } },
        { type: 'gauge', x: 9, y: 0, w: 3, h: 3, config: { title: 'EC-Wert', sensorType: 'ec' } },
      ],
    },
    'sensor-detail': {
      name: 'Sensor-Detail',
      description: 'Live-Chart, Sensor-Karte und 24h-Verlauf für einen Sensor',
      widgets: [
        { type: 'line-chart', x: 0, y: 0, w: 9, h: 4, config: { title: 'Live-Verlauf', timeRange: '1h', showThresholds: false } },
        { type: 'sensor-card', x: 9, y: 0, w: 3, h: 2, config: { title: 'Aktueller Wert' } },
        { type: 'historical', x: 0, y: 4, w: 12, h: 5, config: { title: 'Sensor-Verlauf (24h)', timeRange: '24h' } },
      ],
    },
    'multi-sensor-compare': {
      name: 'Multi-Sensor-Vergleich',
      description: 'Multi-Sensor-Chart zum Vergleichen',
      widgets: [
        { type: 'multi-sensor', x: 0, y: 0, w: 12, h: 6, config: { title: 'Sensor-Vergleich', dataSources: '' } },
      ],
    },
    'empty': {
      name: 'Leer starten',
      description: 'Leeres Dashboard zum freien Gestalten',
      widgets: [],
    },
  }

  /** Create a new layout from a template */
  function createLayoutFromTemplate(templateId: string, name?: string): DashboardLayout | null {
    const template = DASHBOARD_TEMPLATES[templateId]
    if (!template) return null

    const layout: DashboardLayout = {
      id: `dash-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      name: name || template.name,
      description: template.description,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      widgets: template.widgets.map((w, i) => ({
        ...w,
        id: `widget-${Date.now()}-${i}-${Math.random().toString(36).slice(2, 6)}`,
      })),
    }
    layouts.value.push(layout)
    activeLayoutId.value = layout.id
    persistLayouts()
    syncLayoutToServer(layout.id)
    return layout
  }

  /** Cross-zone dashboards (scope === 'cross-zone', filtered by target.view if set) */
  const crossZoneDashboards = computed(() =>
    layouts.value.filter(l => l.scope === 'cross-zone' && (!l.target || l.target.view === 'monitor'))
  )

  /** Zone dashboards filtered by zoneId */
  function zoneDashboards(zoneId: string): DashboardLayout[] {
    return layouts.value.filter(l => l.scope === 'zone' && l.zoneId === zoneId)
  }

  // Category → widget type mapping for auto-generation
  const CATEGORY_WIDGET_MAP: Record<SensorCategoryId, { type: WidgetType; timeRange: '1h' | '24h' }> = {
    temperature: { type: 'line-chart', timeRange: '24h' },
    light:       { type: 'line-chart', timeRange: '24h' },
    air:         { type: 'gauge', timeRange: '1h' },
    water:       { type: 'gauge', timeRange: '1h' },
    soil:        { type: 'gauge', timeRange: '1h' },
    other:       { type: 'sensor-card', timeRange: '1h' },
  }

  /**
   * Auto-generate a zone dashboard based on devices in the zone.
   * Uses SENSOR_TYPE_CONFIG for category-aware widget selection and Y-axis defaults.
   * Layout: time-series (line-chart) at top full-width, gauges middle half-width, actuators bottom.
   */
  function generateZoneDashboard(zoneId: string, devices: { esp_id?: string; sensors?: { gpio: number; sensor_type: string; name?: string | null }[]; actuators?: { gpio: number; actuator_type?: string; name?: string | null }[] }[], zoneName: string): DashboardLayout | null {
    const existing = layouts.value.find(l => l.autoGenerated && l.scope === 'zone' && l.zoneId === zoneId)

    // Collect all sensors and actuators
    type SensorEntry = { espId: string; gpio: number; sensorType: string; name: string | null; category: SensorCategoryId }
    type ActuatorEntry = { espId: string; gpio: number; actuatorType: string; name: string | null }

    const timeSeriesSensors: SensorEntry[] = []
    const gaugeSensors: SensorEntry[] = []
    const otherSensors: SensorEntry[] = []
    const actuators: ActuatorEntry[] = []

    for (const device of devices) {
      const espId = device.esp_id || ''
      for (const s of (device.sensors || [])) {
        const config = SENSOR_TYPE_CONFIG[s.sensor_type]
        const category: SensorCategoryId = config?.category || 'other'
        const mapping = CATEGORY_WIDGET_MAP[category]

        const entry: SensorEntry = {
          espId,
          gpio: s.gpio,
          sensorType: s.sensor_type,
          name: s.name || null,
          category,
        }

        if (mapping.type === 'line-chart') timeSeriesSensors.push(entry)
        else if (mapping.type === 'gauge') gaugeSensors.push(entry)
        else otherSensors.push(entry)
      }

      for (const a of (device.actuators || [])) {
        actuators.push({
          espId,
          gpio: a.gpio,
          actuatorType: a.actuator_type || 'relay',
          name: a.name || null,
        })
      }
    }

    const widgets: DashboardWidget[] = []
    let currentY = 0

    // Row 1: Time-series sensors (full width, h:3 each)
    for (const s of timeSeriesSensors) {
      const config = SENSOR_TYPE_CONFIG[s.sensorType]
      const mapping = CATEGORY_WIDGET_MAP[s.category]
      widgets.push({
        id: `auto-${zoneId}-s-${s.gpio}-${Date.now()}-${widgets.length}`,
        type: 'line-chart',
        x: 0, y: currentY, w: 12, h: 3,
        config: {
          espId: s.espId,
          gpio: s.gpio,
          sensorId: s.espId ? `${s.espId}:${s.gpio}:${s.sensorType}` : undefined,
          sensorType: s.sensorType,
          zoneId,
          title: s.name || config?.label || s.sensorType,
          timeRange: mapping.timeRange,
          showThresholds: true,
          ...(config ? { yMin: config.min, yMax: config.max } : {}),
        },
      })
      currentY += 3
    }

    // Row 2+: Gauges (half width w:6, h:2, 2 per row)
    let gaugeCol = 0
    for (const s of gaugeSensors) {
      const config = SENSOR_TYPE_CONFIG[s.sensorType]
      widgets.push({
        id: `auto-${zoneId}-s-${s.gpio}-${Date.now()}-${widgets.length}`,
        type: 'gauge',
        x: gaugeCol * 6, y: currentY, w: 6, h: 2,
        config: {
          espId: s.espId,
          gpio: s.gpio,
          sensorId: s.espId ? `${s.espId}:${s.gpio}` : undefined,
          sensorType: s.sensorType,
          zoneId,
          title: s.name || config?.label || s.sensorType,
          showThresholds: true,
          ...(config ? { yMin: config.min, yMax: config.max } : {}),
        },
      })
      gaugeCol++
      if (gaugeCol >= 2) { gaugeCol = 0; currentY += 2 }
    }
    if (gaugeCol > 0) currentY += 2 // close partial row

    // Row 3+: Other sensors (sensor-card, half width)
    let otherCol = 0
    for (const s of otherSensors) {
      const config = SENSOR_TYPE_CONFIG[s.sensorType]
      widgets.push({
        id: `auto-${zoneId}-s-${s.gpio}-${Date.now()}-${widgets.length}`,
        type: 'sensor-card',
        x: otherCol * 6, y: currentY, w: 6, h: 2,
        config: {
          espId: s.espId,
          gpio: s.gpio,
          sensorId: s.espId ? `${s.espId}:${s.gpio}` : undefined,
          sensorType: s.sensorType,
          zoneId,
          title: s.name || config?.label || s.sensorType,
        },
      })
      otherCol++
      if (otherCol >= 2) { otherCol = 0; currentY += 2 }
    }
    if (otherCol > 0) currentY += 2

    // Bottom: Actuators (third width w:4, h:2, 3 per row)
    let actCol = 0
    for (const a of actuators) {
      widgets.push({
        id: `auto-${zoneId}-a-${a.gpio}-${Date.now()}-${widgets.length}`,
        type: 'actuator-card',
        x: actCol * 4, y: currentY, w: 4, h: 2,
        config: {
          espId: a.espId,
          gpio: a.gpio,
          actuatorId: a.espId ? `${a.espId}:${a.gpio}` : undefined,
          zoneId,
          title: a.name || a.actuatorType,
        },
      })
      actCol++
      if (actCol >= 3) { actCol = 0; currentY += 2 }
    }

    if (widgets.length === 0) return null

    if (existing) {
      const idx = layouts.value.findIndex(l => l.id === existing.id)
      if (idx !== -1) {
        layouts.value[idx] = {
          ...existing,
          widgets,
          updatedAt: new Date().toISOString(),
        }
        persistLayouts()
        syncLayoutToServer(existing.id)
        return layouts.value[idx]
      }
    }

    const layout: DashboardLayout = {
      id: `dash-auto-${zoneId}-${Date.now()}`,
      name: `${zoneName} Dashboard`,
      description: `Automatisch generiert für Zone ${zoneName}`,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      widgets,
      scope: 'zone',
      zoneId,
      autoGenerated: true,
    }
    layouts.value.push(layout)
    persistLayouts()
    syncLayoutToServer(layout.id)
    return layout
  }

  /**
   * Convert an auto-generated dashboard to a user-editable one.
   * Sets autoGenerated to false so it won't be overwritten.
   */
  function claimAutoLayout(layoutId: string) {
    const idx = layouts.value.findIndex(l => l.id === layoutId)
    if (idx === -1) return
    layouts.value[idx] = {
      ...layouts.value[idx],
      autoGenerated: false,
      updatedAt: new Date().toISOString(),
    }
    persistLayouts()
    syncLayoutToServer(layoutId)
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // TARGET-BASED COMPUTED VIEWS (Phase 4 — Block 7b)
  // ═══════════════════════════════════════════════════════════════════════════

  /** Base filter: monitor + inline placement */
  const _inlineMonitorBase = (l: DashboardLayout) =>
    l.target?.view === 'monitor' && l.target?.placement === 'inline'

  /** Cross-zone inline panels (scope !== 'zone' or scope null) — shown on L1 and L2 */
  const inlineMonitorPanelsCrossZone = computed(() =>
    layouts.value
      .filter(l => _inlineMonitorBase(l) && (l.scope !== 'zone' || l.scope == null))
      .sort((a, b) => (a.target?.order ?? 0) - (b.target?.order ?? 0))
  )

  /** Zone-specific inline panels for a given zone — shown only on L2 when zoneId matches */
  function inlineMonitorPanelsForZone(zoneId: string): DashboardLayout[] {
    return layouts.value
      .filter(l => _inlineMonitorBase(l) && l.scope === 'zone' && l.zoneId === zoneId)
      .sort((a, b) => (a.target?.order ?? 0) - (b.target?.order ?? 0))
  }

  /** All inline panels for L1 (cross-zone only) — backward compat alias */
  const inlineMonitorPanels = inlineMonitorPanelsCrossZone

  /** Dashboards targeted as side panels in Monitor view */
  const sideMonitorPanels = computed(() =>
    layouts.value.filter(l => l.target?.view === 'monitor' && l.target?.placement === 'side-panel')
      .sort((a, b) => (a.target?.order ?? 0) - (b.target?.order ?? 0))
  )

  /** Dashboards targeted as bottom panels in Monitor view */
  const bottomMonitorPanels = computed(() =>
    layouts.value.filter(l => l.target?.view === 'monitor' && l.target?.placement === 'bottom-panel')
      .sort((a, b) => (a.target?.order ?? 0) - (b.target?.order ?? 0))
  )

  /** Dashboards targeted for display in Hardware view */
  const hardwarePanels = computed(() =>
    layouts.value.filter(l => l.target?.view === 'hardware')
      .sort((a, b) => (a.target?.order ?? 0) - (b.target?.order ?? 0))
  )

  /** Set display target for a layout. Enforces uniqueness: clears conflicting target from other layouts. */
  function setLayoutTarget(layoutId: string, target: DashboardTarget | null) {
    const idx = layouts.value.findIndex(l => l.id === layoutId)
    if (idx === -1) return

    // Enforce target uniqueness: only one dashboard per view+placement slot
    if (target) {
      const existingHolder = layouts.value.find(l =>
        l.id !== layoutId &&
        l.target?.view === target.view &&
        l.target?.placement === target.placement
      )
      if (existingHolder) {
        const holderIdx = layouts.value.findIndex(l => l.id === existingHolder.id)
        if (holderIdx !== -1) {
          layouts.value[holderIdx] = {
            ...layouts.value[holderIdx],
            target: undefined,
            updatedAt: new Date().toISOString(),
          }
          syncLayoutToServer(existingHolder.id)
          logger.info(`Target conflict: cleared target from "${existingHolder.name}" (replaced by "${layouts.value[idx].name}")`)
        }
      }
    }

    layouts.value[idx] = {
      ...layouts.value[idx],
      target: target || undefined,
      updatedAt: new Date().toISOString(),
    }
    persistLayouts()
    syncLayoutToServer(layoutId)
  }

  // Auto-load on store creation: localStorage first (instant), then server sync (async)
  loadLayouts()
  fetchLayouts().catch(() => {
    // Error already handled inside fetchLayouts — this prevents unhandled promise rejection
  })

  return {
    showControls,
    statusCounts,
    deviceCounts,
    pendingCount,
    activeStatusFilters,
    filterType,
    breadcrumb,
    showCreateMock,
    showPendingPanel,
    navRequestCount,
    navTarget,
    hasProblems,
    problemMessage,
    hasPendingDevices,
    toggleStatusFilter,
    resetFilters,
    activate,
    deactivate,
    requestNavigate,

    // Custom Dashboard Layout (Phase 2 + Phase 3 Server Sync)
    layouts,
    activeLayoutId,
    activeLayout,
    getLayoutById,
    isSyncing,
    lastSyncError,
    loadLayouts,
    fetchLayouts,
    createLayout,
    saveLayout,
    deleteLayout,
    exportLayout,
    importLayout,
    crossZoneDashboards,
    zoneDashboards,
    generateZoneDashboard,
    claimAutoLayout,
    DASHBOARD_TEMPLATES,
    createLayoutFromTemplate,

    // Target-based panel views (Phase 4 — Block 7)
    inlineMonitorPanels,
    inlineMonitorPanelsCrossZone,
    inlineMonitorPanelsForZone,
    sideMonitorPanels,
    bottomMonitorPanels,
    hardwarePanels,
    setLayoutTarget,
  }
})
