/**
 * Dashboard Store
 *
 * Bridge between HardwareView and TopBar (UI consumer).
 * statusCounts are computed from espStore via getESPStatus (reactive).
 * TopBar reads counts/breadcrumb and writes filter changes.
 *
 * Extended with Custom Dashboard Layout management (Phase 2).
 */

import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import { useEspStore } from '@/stores/esp'
import { getESPStatus } from '@/composables/useESPStatus'

export type StatusFilter = 'online' | 'offline' | 'warning' | 'safemode'
export type TypeFilter = 'all' | 'mock' | 'real'

/** Widget type identifiers */
export type WidgetType = 'line-chart' | 'gauge' | 'sensor-card' |
  'historical' | 'actuator-card' | 'actuator-runtime' |
  'esp-health' | 'alarm-list' | 'multi-sensor'

/** Single widget configuration */
export interface DashboardWidget {
  id: string
  type: WidgetType
  x: number
  y: number
  w: number
  h: number
  config: {
    sensorId?: string
    actuatorId?: string
    espId?: string
    gpio?: number
    sensorType?: string
    zoneId?: string
    timeRange?: '1h' | '6h' | '24h' | '7d' | 'custom'
    showThresholds?: boolean
    title?: string
    color?: string
    syncTimeAxis?: boolean
    /** Comma-separated sensor IDs for multi-sensor widget */
    dataSources?: string
    /** Explicit Y-axis min override */
    yMin?: number
    /** Explicit Y-axis max override */
    yMax?: number
  }
}

/** Dashboard scope */
export type DashboardScope = 'zone' | 'cross-zone' | 'sensor-detail'

/** Dashboard layout */
export interface DashboardLayout {
  id: string
  name: string
  description?: string
  createdAt: string
  updatedAt: string
  widgets: DashboardWidget[]
  scope?: DashboardScope
  zoneId?: string
  autoGenerated?: boolean
  sensorId?: string
}

export const useDashboardStore = defineStore('dashboard', () => {
  const espStore = useEspStore()

  /* ── Visibility ── */
  const showControls = ref(false)

  /* ── Counts (computed from espStore via getESPStatus — reactive to device changes) ── */
  const statusCounts = computed(() => {
    let online = 0, offline = 0, warning = 0, safeMode = 0
    for (const device of espStore.devices) {
      const status = getESPStatus(device)
      switch (status) {
        case 'online':
        case 'stale':
          online++
          break
        case 'offline':
        case 'unknown':
          offline++
          break
        case 'error':
          warning++
          break
        case 'safemode':
          safeMode++
          break
      }
    }
    return { online, offline, warning, safeMode }
  })

  /* ── Device counts (computed from espStore — reactive to device changes) ── */
  const deviceCounts = computed(() => ({
    all: espStore.devices.length,
    mock: espStore.mockDevices.length,
    real: espStore.realDevices.length,
  }))
  const pendingCount = computed(() => espStore.pendingCount)

  /* ── Filters (bidirectional: TopBar writes, DashboardView reads) ── */
  const activeStatusFilters = ref<Set<StatusFilter>>(new Set())
  const filterType = ref<TypeFilter>('all')

  /* ── Breadcrumb (written by Views, read by TopBar) ── */
  const breadcrumb = ref<{
    level: 1 | 2 | 3
    zoneName: string
    deviceName: string
    sensorName: string
    ruleName: string
    dashboardName: string
  }>({
    level: 1,
    zoneName: '',
    deviceName: '',
    sensorName: '',
    ruleName: '',
    dashboardName: '',
  })

  /* ── Modal/Panel triggers (TopBar writes, DashboardView reads) ── */
  const showCreateMock = ref(false)
  const showPendingPanel = ref(false)

  /* ── Navigation request (TopBar → DashboardView) ── */
  const navRequestCount = ref(0)
  const navTarget = ref<1 | 2 | 3>(1)

  /* ── Computed ── */
  const hasProblems = computed(() =>
    statusCounts.value.warning > 0 || statusCounts.value.safeMode > 0
  )

  const problemMessage = computed(() => {
    const { warning, safeMode, offline, online } = statusCounts.value
    if (warning > 0) return `${warning} Gerät(e) mit Fehlern`
    if (safeMode > 0) return `${safeMode} Gerät(e) im Safe-Mode`
    if (offline > 0 && online > 0) return `${offline} Gerät(e) offline`
    return ''
  })

  const hasPendingDevices = computed(() => pendingCount.value > 0)

  /* ── Actions ── */
  function toggleStatusFilter(filter: StatusFilter) {
    const next = new Set(activeStatusFilters.value)
    if (next.has(filter)) next.delete(filter)
    else next.add(filter)
    activeStatusFilters.value = next
  }

  function resetFilters() {
    filterType.value = 'all'
    activeStatusFilters.value = new Set()
  }

  function activate() {
    showControls.value = true
  }

  function deactivate() {
    showControls.value = false
    resetFilters()
  }

  function requestNavigate(level: 1 | 2 | 3) {
    navTarget.value = level
    navRequestCount.value++
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // CUSTOM DASHBOARD LAYOUTS (Phase 2)
  // ═══════════════════════════════════════════════════════════════════════════

  const STORAGE_KEY = 'automation-one-dashboard-layouts'

  /** All saved layouts */
  const layouts = ref<DashboardLayout[]>([])
  /** Currently active layout ID */
  const activeLayoutId = ref<string | null>(null)

  /** Currently active layout */
  const activeLayout = computed<DashboardLayout | null>(() =>
    layouts.value.find(l => l.id === activeLayoutId.value) ?? null
  )

  /** Load layouts from localStorage */
  function loadLayouts() {
    try {
      const stored = localStorage.getItem(STORAGE_KEY)
      if (stored) {
        layouts.value = JSON.parse(stored)
        if (layouts.value.length > 0 && !activeLayoutId.value) {
          activeLayoutId.value = layouts.value[0].id
        }
      }
    } catch {
      layouts.value = []
    }
  }

  /** Persist layouts to localStorage */
  function persistLayouts() {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(layouts.value))
    } catch {
      // localStorage full or unavailable
    }
  }

  /** Create a new dashboard layout */
  function createLayout(name: string, description?: string): DashboardLayout {
    const layout: DashboardLayout = {
      id: `dash-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      name,
      description,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      widgets: [],
    }
    layouts.value.push(layout)
    activeLayoutId.value = layout.id
    persistLayouts()
    return layout
  }

  /** Save current layout widgets */
  function saveLayout(layoutId: string, widgets: DashboardWidget[]) {
    const idx = layouts.value.findIndex(l => l.id === layoutId)
    if (idx === -1) return
    layouts.value[idx] = {
      ...layouts.value[idx],
      widgets,
      updatedAt: new Date().toISOString(),
    }
    persistLayouts()
  }

  /** Delete a layout */
  function deleteLayout(layoutId: string) {
    layouts.value = layouts.value.filter(l => l.id !== layoutId)
    if (activeLayoutId.value === layoutId) {
      activeLayoutId.value = layouts.value[0]?.id ?? null
    }
    persistLayouts()
  }

  /** Export layout as JSON string */
  function exportLayout(layoutId: string): string | null {
    const layout = layouts.value.find(l => l.id === layoutId)
    if (!layout) return null
    return JSON.stringify(layout, null, 2)
  }

  /** Import layout from JSON string */
  function importLayout(json: string): DashboardLayout | null {
    try {
      const layout = JSON.parse(json) as DashboardLayout
      layout.id = `dash-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
      layout.createdAt = new Date().toISOString()
      layout.updatedAt = new Date().toISOString()
      layouts.value.push(layout)
      persistLayouts()
      return layout
    } catch {
      return null
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // DASHBOARD TEMPLATES
  // ═══════════════════════════════════════════════════════════════════════════

  /** Pre-defined dashboard templates */
  const DASHBOARD_TEMPLATES: Record<string, { name: string; description: string; widgets: Omit<DashboardWidget, 'id'>[] }> = {
    'zone-overview': {
      name: 'Zonen-Übersicht',
      description: '4 Gauges für Temperatur, Luftfeuchtigkeit, pH und EC',
      widgets: [
        { type: 'gauge', x: 0, y: 0, w: 3, h: 3, config: { title: 'Temperatur', sensorType: 'temperature' } },
        { type: 'gauge', x: 3, y: 0, w: 3, h: 3, config: { title: 'Luftfeuchtigkeit', sensorType: 'humidity' } },
        { type: 'gauge', x: 6, y: 0, w: 3, h: 3, config: { title: 'pH-Wert', sensorType: 'ph' } },
        { type: 'gauge', x: 9, y: 0, w: 3, h: 3, config: { title: 'EC-Wert', sensorType: 'ec' } },
      ],
    },
    'sensor-detail': {
      name: 'Sensor-Detail',
      description: 'Großes Linien-Chart für einen Sensor (24h)',
      widgets: [
        { type: 'historical', x: 0, y: 0, w: 12, h: 6, config: { title: 'Sensor-Verlauf', timeRange: '24h' } },
      ],
    },
    'multi-sensor-compare': {
      name: 'Multi-Sensor-Vergleich',
      description: 'Multi-Sensor-Chart zum Vergleichen',
      widgets: [
        { type: 'multi-sensor', x: 0, y: 0, w: 12, h: 6, config: { title: 'Sensor-Vergleich', dataSources: '' } },
      ],
    },
    'empty': {
      name: 'Leer starten',
      description: 'Leeres Dashboard zum freien Gestalten',
      widgets: [],
    },
  }

  /** Create a new layout from a template */
  function createLayoutFromTemplate(templateId: string, name?: string): DashboardLayout | null {
    const template = DASHBOARD_TEMPLATES[templateId]
    if (!template) return null

    const layout: DashboardLayout = {
      id: `dash-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      name: name || template.name,
      description: template.description,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      widgets: template.widgets.map((w, i) => ({
        ...w,
        id: `widget-${Date.now()}-${i}-${Math.random().toString(36).slice(2, 6)}`,
      })),
    }
    layouts.value.push(layout)
    activeLayoutId.value = layout.id
    persistLayouts()
    return layout
  }

  /** Cross-zone dashboards (scope === 'cross-zone') */
  const crossZoneDashboards = computed(() =>
    layouts.value.filter(l => l.scope === 'cross-zone')
  )

  /** Zone dashboards filtered by zoneId */
  function zoneDashboards(zoneId: string): DashboardLayout[] {
    return layouts.value.filter(l => l.scope === 'zone' && l.zoneId === zoneId)
  }

  /**
   * Auto-generate a zone dashboard based on devices in the zone.
   * Only creates if no auto-generated layout exists for this zone.
   * Updates existing auto-generated layouts.
   */
  function generateZoneDashboard(zoneId: string, devices: { sensors?: { gpio: number; sensor_type: string; name?: string | null }[]; actuators?: { gpio: number; actuator_type?: string; name?: string | null }[] }[], zoneName: string): DashboardLayout | null {
    // Check for existing auto-generated layout
    const existing = layouts.value.find(l => l.autoGenerated && l.scope === 'zone' && l.zoneId === zoneId)

    const widgets: DashboardWidget[] = []
    let col = 0
    let row = 0
    const COLS = 2

    // Sensor type → widget type mapping
    const sensorWidgetMap: Record<string, WidgetType> = {
      temperature: 'line-chart',
      humidity: 'gauge',
      pressure: 'gauge',
      ph: 'gauge',
      ec: 'gauge',
      moisture: 'gauge',
      light: 'line-chart',
      co2: 'line-chart',
    }

    // Generate sensor widgets
    for (const device of devices) {
      const sensors = device.sensors || []
      for (const s of sensors) {
        const baseType = s.sensor_type?.toLowerCase()?.replace(/[_\d]+/g, '') || 'other'
        const widgetType = sensorWidgetMap[baseType] || 'sensor-card'

        widgets.push({
          id: `auto-${zoneId}-s-${s.gpio}-${Date.now()}`,
          type: widgetType,
          x: col * 6,
          y: row * 4,
          w: 6,
          h: 4,
          config: {
            gpio: s.gpio,
            sensorType: s.sensor_type,
            zoneId,
            title: s.name || s.sensor_type,
            timeRange: '1h',
            showThresholds: true,
          },
        })

        col++
        if (col >= COLS) {
          col = 0
          row++
        }
      }
    }

    if (widgets.length === 0) return null

    if (existing) {
      // Update existing auto-generated layout
      const idx = layouts.value.findIndex(l => l.id === existing.id)
      if (idx !== -1) {
        layouts.value[idx] = {
          ...existing,
          widgets,
          updatedAt: new Date().toISOString(),
        }
        persistLayouts()
        return layouts.value[idx]
      }
    }

    // Create new auto-generated layout
    const layout: DashboardLayout = {
      id: `dash-auto-${zoneId}-${Date.now()}`,
      name: `${zoneName} Dashboard`,
      description: `Automatisch generiert für Zone ${zoneName}`,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      widgets,
      scope: 'zone',
      zoneId,
      autoGenerated: true,
    }
    layouts.value.push(layout)
    persistLayouts()
    return layout
  }

  /**
   * Convert an auto-generated dashboard to a user-editable one.
   * Sets autoGenerated to false so it won't be overwritten.
   */
  function claimAutoLayout(layoutId: string) {
    const idx = layouts.value.findIndex(l => l.id === layoutId)
    if (idx === -1) return
    layouts.value[idx] = {
      ...layouts.value[idx],
      autoGenerated: false,
      updatedAt: new Date().toISOString(),
    }
    persistLayouts()
  }

  // Auto-load on store creation
  loadLayouts()

  return {
    showControls,
    statusCounts,
    deviceCounts,
    pendingCount,
    activeStatusFilters,
    filterType,
    breadcrumb,
    showCreateMock,
    showPendingPanel,
    navRequestCount,
    navTarget,
    hasProblems,
    problemMessage,
    hasPendingDevices,
    toggleStatusFilter,
    resetFilters,
    activate,
    deactivate,
    requestNavigate,

    // Custom Dashboard Layout (Phase 2)
    layouts,
    activeLayoutId,
    activeLayout,
    loadLayouts,
    createLayout,
    saveLayout,
    deleteLayout,
    exportLayout,
    importLayout,
    crossZoneDashboards,
    zoneDashboards,
    generateZoneDashboard,
    claimAutoLayout,
    DASHBOARD_TEMPLATES,
    createLayoutFromTemplate,
  }
})
