<script setup lang="ts">
/**
 * WidgetConfigPanel — SlideOver panel for configuring dashboard widgets
 *
 * 3-Zone Progressive Disclosure Layout:
 *   Zone 1 (KERN): Title, Zone-Filter, Sensor/Actuator, Time Range — always visible
 *   Zone 2 (DARSTELLUNG): Y-Axis, Color, Thresholds — accordion, collapsed by default
 *   Zone 3 (ERWEITERT): Statistics options — accordion, collapsed by default
 */
import { ref, computed, watch } from 'vue'
import { ChevronRight, Download } from 'lucide-vue-next'
import { useEspStore } from '@/stores/esp'
import { SlideOver } from '@/shared/design/primitives'
import { SENSOR_TYPE_CONFIG } from '@/utils/sensorDefaults'
import { CHART_COLORS } from '@/utils/chartColors'
import { useSensorOptions } from '@/composables/useSensorOptions'
import { sensorsApi } from '@/api/sensors'
import type { MockActuator } from '@/types'

interface Props {
  open: boolean
  widgetId: string
  widgetType: string
  config: Record<string, any>
  /** Zone ID for pre-filtering sensor options in zone-scoped dashboards (PA-02c) */
  zoneId?: string
}

const props = defineProps<Props>()
const emit = defineEmits<{
  close: []
  'update:config': [config: Record<string, any>]
}>()

const espStore = useEspStore()

// Local config copy for editing
const localConfig = ref<Record<string, any>>({})

watch(() => props.config, (cfg) => {
  localConfig.value = { ...cfg }
}, { immediate: true, deep: true })

// Determine which fields to show based on widget type
const hasSensorField = computed(() =>
  ['line-chart', 'gauge', 'sensor-card', 'historical', 'statistics'].includes(props.widgetType)
)
const hasActuatorField = computed(() =>
  ['actuator-card'].includes(props.widgetType)
)
const hasTimeRange = computed(() =>
  ['historical', 'statistics'].includes(props.widgetType)
)
const hasYRange = computed(() =>
  ['line-chart', 'historical', 'gauge'].includes(props.widgetType)
)

/** Threshold fields — same widget types as Y-axis (line-chart, gauge, historical) */
const hasThresholdFields = computed(() =>
  ['line-chart', 'gauge', 'historical'].includes(props.widgetType)
)

/** Widgets that support zoneFilter (AlarmListWidget, ESPHealthWidget, ActuatorRuntimeWidget) */
const hasZoneFilterField = computed(() =>
  ['alarm-list', 'esp-health', 'actuator-runtime'].includes(props.widgetType)
)

const hasStatisticsOptions = computed(() =>
  props.widgetType === 'statistics'
)

// Zone 3 is visible only for statistics widgets
const hasZone3 = computed(() =>
  hasStatisticsOptions.value
)

// Zone filter for sensor selection — defaults to dashboard zoneId (PA-02c)
const selectedSensorZone = ref<string | undefined>(props.zoneId)

// Sync zone filter when dashboard zoneId changes
watch(() => props.zoneId, (v) => { selectedSensorZone.value = v })

// Centralized sensor options (deduplicated, zone-grouped)
const { groupedSensorOptions } = useSensorOptions(selectedSensorZone)

// Available zones (derived from grouped sensor options)
const availableZones = computed(() => {
  const seen = new Set<string>()
  const list: { id: string; name: string }[] = []
  for (const d of espStore.devices) {
    if (d.zone_id && !seen.has(d.zone_id)) {
      seen.add(d.zone_id)
      list.push({ id: d.zone_id, name: d.zone_name || d.zone_id })
    }
  }
  return list.sort((a, b) => (a.name || a.id).localeCompare(b.name || b.id))
})

// Available actuators
const availableActuators = computed(() => {
  const items: { id: string; label: string }[] = []
  for (const device of espStore.devices) {
    const deviceId = espStore.getDeviceId(device)
    for (const a of (device.actuators as MockActuator[]) || []) {
      items.push({
        id: `${deviceId}:${a.gpio}`,
        label: `${a.name || a.actuator_type} (${deviceId})`,
      })
    }
  }
  return items
})

// Find sensor type from grouped options for Y-range hints
function findSensorType(sensorId: string): string | null {
  for (const group of groupedSensorOptions.value) {
    for (const subgroup of group.subgroups) {
      const opt = subgroup.options.find(o => o.value === sensorId)
      if (opt) return opt.sensorType
    }
  }
  return null
}

// Current sensor type config for Y-range hints
const sensorTypeConfig = computed(() => {
  if (!localConfig.value.sensorId) return null
  const type = findSensorType(localConfig.value.sensorId)
  if (!type) return null
  return SENSOR_TYPE_CONFIG[type] || null
})

function updateField(field: string, value: any) {
  localConfig.value = { ...localConfig.value, [field]: value }
  emit('update:config', localConfig.value)
}

function isAutoGeneratedTitle(title: string | undefined | null): boolean {
  if (!title) return true
  const knownLabels = new Set(
    Object.values(SENSOR_TYPE_CONFIG).map(c => c.label)
  )
  const knownTypes = new Set(Object.keys(SENSOR_TYPE_CONFIG))
  return knownLabels.has(title) || knownTypes.has(title)
}

function handleSensorChange(sensorId: string) {
  const sType = findSensorType(sensorId)
  const updates: Record<string, any> = { sensorId }

  if (sType) {
    const cfg = SENSOR_TYPE_CONFIG[sType]
    if (cfg) {
      updates.yMin = cfg.min
      updates.yMax = cfg.max
      if (isAutoGeneratedTitle(localConfig.value.title)) {
        updates.title = cfg.label
      }
    } else {
      updates.yMin = null
      updates.yMax = null
      if (isAutoGeneratedTitle(localConfig.value.title)) {
        updates.title = sType
      }
    }
  }

  localConfig.value = { ...localConfig.value, ...updates }
  emit('update:config', localConfig.value)
}

function handleActuatorChange(actuatorId: string) {
  updateField('actuatorId', actuatorId)
}

// --- Alert-Config Threshold Sync (P8-A3) ---

/** Find the config_id (UUID) for the currently selected sensor */
function findSensorConfigId(sensorId: string): string | undefined {
  for (const group of groupedSensorOptions.value) {
    for (const subgroup of group.subgroups) {
      const opt = subgroup.options.find(o => o.value === sensorId)
      if (opt?.configId) return opt.configId
    }
  }
  return undefined
}

const isLoadingThresholds = ref(false)
const thresholdSyncMessage = ref<string | null>(null)
let syncMessageTimer: ReturnType<typeof setTimeout> | undefined

function showSyncMessage(msg: string) {
  thresholdSyncMessage.value = msg
  clearTimeout(syncMessageTimer)
  syncMessageTimer = setTimeout(() => { thresholdSyncMessage.value = null }, 3000)
}

async function loadThresholdsFromAlertConfig(): Promise<void> {
  const sensorId = localConfig.value.sensorId
  if (!sensorId) {
    showSyncMessage('Kein Sensor ausgewählt')
    return
  }

  const configId = findSensorConfigId(sensorId)
  if (!configId) {
    showSyncMessage('Sensor hat keine Config-ID')
    return
  }

  isLoadingThresholds.value = true
  try {
    const response = await sensorsApi.getAlertConfig(configId)
    const thresholds = (response.alert_config as Record<string, any>)?.custom_thresholds as
      | { warning_min?: number | null; warning_max?: number | null; critical_min?: number | null; critical_max?: number | null }
      | undefined

    if (!thresholds || (thresholds.warning_min == null && thresholds.warning_max == null && thresholds.critical_min == null && thresholds.critical_max == null)) {
      showSyncMessage('Keine Schwellwerte für diesen Sensor konfiguriert')
      return
    }

    const updates: Record<string, any> = { ...localConfig.value, showThresholds: true }
    if (thresholds.warning_min != null) updates.warnLow = thresholds.warning_min
    if (thresholds.warning_max != null) updates.warnHigh = thresholds.warning_max
    if (thresholds.critical_min != null) updates.alarmLow = thresholds.critical_min
    if (thresholds.critical_max != null) updates.alarmHigh = thresholds.critical_max

    localConfig.value = updates
    emit('update:config', localConfig.value)
    showSyncMessage('Schwellen geladen')
  } catch {
    showSyncMessage('Laden fehlgeschlagen')
  } finally {
    isLoadingThresholds.value = false
  }
}

const widgetTypeLabels: Record<string, string> = {
  'line-chart': 'Linien-Chart',
  'gauge': 'Gauge',
  'sensor-card': 'Sensor-Karte',
  'historical': 'Historische Zeitreihe',
  'actuator-card': 'Aktor-Status',
  'actuator-runtime': 'Aktor-Laufzeit',
  'esp-health': 'ESP-Health',
  'alarm-list': 'Alarm-Liste',
  'multi-sensor': 'Multi-Sensor-Chart',
  'statistics': 'Statistik',
}
</script>

<template>
  <SlideOver
    :open="open"
    :title="`${widgetTypeLabels[widgetType] || widgetType} konfigurieren`"
    width="sm"
    @close="emit('close')"
  >
    <div class="widget-config-panel">

      <!-- ═══════════════════════════════════════════════════════
           ZONE 1: KERN — always visible, max 5 fields
           ═══════════════════════════════════════════════════════ -->

      <!-- Title -->
      <div class="widget-config-panel__field">
        <label class="widget-config-panel__label">Titel</label>
        <input
          type="text"
          class="widget-config-panel__input"
          :value="localConfig.title || ''"
          placeholder="Widget-Titel..."
          @input="updateField('title', ($event.target as HTMLInputElement).value)"
        />
      </div>

      <!-- Zone Filter for Sensor Selection -->
      <div v-if="hasSensorField" class="widget-config-panel__field">
        <label class="widget-config-panel__label">Zone</label>
        <select
          class="widget-config-panel__select"
          :value="selectedSensorZone || ''"
          @change="selectedSensorZone = ($event.target as HTMLSelectElement).value || undefined"
        >
          <option value="">Alle Zonen</option>
          <option
            v-for="z in availableZones"
            :key="z.id"
            :value="z.id"
          >{{ z.name }}</option>
        </select>
      </div>

      <!-- Zone Filter (AlarmListWidget, ESPHealthWidget, ActuatorRuntimeWidget) -->
      <div v-if="hasZoneFilterField" class="widget-config-panel__field">
        <label class="widget-config-panel__label">Zone-Filter</label>
        <select
          class="widget-config-panel__select"
          :value="localConfig.zoneFilter ?? ''"
          @change="updateField('zoneFilter', ($event.target as HTMLSelectElement).value || null)"
          aria-label="Anzeige für Zone"
        >
          <option value="">Alle Zonen</option>
          <option
            v-for="z in availableZones"
            :key="z.id"
            :value="z.id"
          >{{ z.name }}</option>
        </select>
      </div>

      <!-- Sensor Selection (grouped by Zone / Subzone) -->
      <div v-if="hasSensorField" class="widget-config-panel__field">
        <label class="widget-config-panel__label">Sensor</label>
        <select
          class="widget-config-panel__select"
          :value="localConfig.sensorId || ''"
          @change="handleSensorChange(($event.target as HTMLSelectElement).value)"
        >
          <option value="" disabled>— Sensor wählen —</option>
          <template v-for="zoneGroup in groupedSensorOptions" :key="zoneGroup.zoneId ?? '__unassigned'">
            <template v-for="subgroup in zoneGroup.subgroups" :key="`${zoneGroup.zoneId}_${subgroup.subzoneId ?? '__nosub'}`">
              <optgroup :label="subgroup.label ? `${zoneGroup.label} / ${subgroup.label}` : zoneGroup.label">
                <option
                  v-for="opt in subgroup.options"
                  :key="opt.value"
                  :value="opt.value"
                >{{ opt.label }}</option>
              </optgroup>
            </template>
          </template>
        </select>
      </div>

      <!-- Actuator Selection -->
      <div v-if="hasActuatorField" class="widget-config-panel__field">
        <label class="widget-config-panel__label">Aktor</label>
        <select
          class="widget-config-panel__select"
          :value="localConfig.actuatorId || ''"
          @change="handleActuatorChange(($event.target as HTMLSelectElement).value)"
        >
          <option value="" disabled>— Aktor wählen —</option>
          <option
            v-for="a in availableActuators"
            :key="a.id"
            :value="a.id"
          >{{ a.label }}</option>
        </select>
      </div>

      <!-- Time Range (Historical, Statistics) -->
      <div v-if="hasTimeRange" class="widget-config-panel__field">
        <label class="widget-config-panel__label">Zeitraum</label>
        <div class="widget-config-panel__chips">
          <button
            v-for="range in ['1h', '6h', '24h', '7d', '30d']"
            :key="range"
            :class="['widget-config-panel__chip', { 'widget-config-panel__chip--active': localConfig.timeRange === range }]"
            @click="updateField('timeRange', range)"
          >{{ range }}</button>
        </div>
      </div>

      <!-- ═══════════════════════════════════════════════════════
           ZONE 2: DARSTELLUNG — accordion, collapsed by default
           ═══════════════════════════════════════════════════════ -->

      <details class="config-section">
        <summary class="config-section__header">
          <ChevronRight :size="16" class="config-section__chevron" />
          <span>Darstellung</span>
        </summary>
        <div class="config-section__body">

          <!-- Y-Axis Range (Charts) -->
          <div v-if="hasYRange" class="widget-config-panel__field">
            <label class="widget-config-panel__label">
              Y-Achse
              <span v-if="sensorTypeConfig" class="widget-config-panel__hint">
                ({{ sensorTypeConfig.label }}: {{ sensorTypeConfig.min }}–{{ sensorTypeConfig.max }} {{ sensorTypeConfig.unit }})
              </span>
            </label>
            <div class="widget-config-panel__range-row">
              <input
                type="number"
                class="widget-config-panel__input widget-config-panel__input--small"
                :value="localConfig.yMin ?? ''"
                placeholder="Min (auto)"
                @input="updateField('yMin', ($event.target as HTMLInputElement).value ? Number(($event.target as HTMLInputElement).value) : undefined)"
              />
              <span class="widget-config-panel__range-sep">–</span>
              <input
                type="number"
                class="widget-config-panel__input widget-config-panel__input--small"
                :value="localConfig.yMax ?? ''"
                placeholder="Max (auto)"
                @input="updateField('yMax', ($event.target as HTMLInputElement).value ? Number(($event.target as HTMLInputElement).value) : undefined)"
              />
            </div>
          </div>

          <!-- Color -->
          <div class="widget-config-panel__field">
            <label class="widget-config-panel__label">Farbe</label>
            <div class="widget-config-panel__color-row">
              <button
                v-for="c in CHART_COLORS"
                :key="c"
                :class="['widget-config-panel__color-swatch', { 'widget-config-panel__color-swatch--active': localConfig.color === c }]"
                :style="{ background: c }"
                @click="updateField('color', c)"
              />
            </div>
          </div>

          <!-- Thresholds toggle -->
          <div v-if="hasThresholdFields" class="widget-config-panel__field">
            <label class="widget-config-panel__label-row">
              <span>Schwellenwerte anzeigen</span>
              <input
                type="checkbox"
                :checked="localConfig.showThresholds ?? false"
                @change="updateField('showThresholds', ($event.target as HTMLInputElement).checked)"
              />
            </label>
          </div>

          <!-- Load thresholds from alert-config (P8-A3) -->
          <div v-if="hasThresholdFields && localConfig.showThresholds && localConfig.sensorId" class="widget-config-panel__field">
            <button
              class="widget-config-panel__sync-btn"
              :disabled="isLoadingThresholds"
              @click="loadThresholdsFromAlertConfig"
            >
              <Download :size="14" />
              <span>{{ isLoadingThresholds ? 'Laden…' : 'Schwellen aus Sensor-Config laden' }}</span>
            </button>
            <Transition name="sync-msg">
              <span v-if="thresholdSyncMessage" class="widget-config-panel__sync-msg">
                {{ thresholdSyncMessage }}
              </span>
            </Transition>
          </div>

          <!-- Threshold values (when enabled) -->
          <div v-if="hasThresholdFields && localConfig.showThresholds" class="widget-config-panel__field">
            <label class="widget-config-panel__label">Alarm-Schwellen</label>
            <div class="widget-config-panel__threshold-grid">
              <div class="widget-config-panel__threshold-row">
                <span class="widget-config-panel__threshold-label widget-config-panel__threshold-label--alarm">Alarm Low</span>
                <input
                  type="number"
                  class="widget-config-panel__input widget-config-panel__input--small"
                  :value="localConfig.alarmLow ?? ''"
                  placeholder="—"
                  @input="updateField('alarmLow', ($event.target as HTMLInputElement).value ? Number(($event.target as HTMLInputElement).value) : undefined)"
                />
              </div>
              <div class="widget-config-panel__threshold-row">
                <span class="widget-config-panel__threshold-label widget-config-panel__threshold-label--warn">Warn Low</span>
                <input
                  type="number"
                  class="widget-config-panel__input widget-config-panel__input--small"
                  :value="localConfig.warnLow ?? ''"
                  placeholder="—"
                  @input="updateField('warnLow', ($event.target as HTMLInputElement).value ? Number(($event.target as HTMLInputElement).value) : undefined)"
                />
              </div>
              <div class="widget-config-panel__threshold-row">
                <span class="widget-config-panel__threshold-label widget-config-panel__threshold-label--warn">Warn High</span>
                <input
                  type="number"
                  class="widget-config-panel__input widget-config-panel__input--small"
                  :value="localConfig.warnHigh ?? ''"
                  placeholder="—"
                  @input="updateField('warnHigh', ($event.target as HTMLInputElement).value ? Number(($event.target as HTMLInputElement).value) : undefined)"
                />
              </div>
              <div class="widget-config-panel__threshold-row">
                <span class="widget-config-panel__threshold-label widget-config-panel__threshold-label--alarm">Alarm High</span>
                <input
                  type="number"
                  class="widget-config-panel__input widget-config-panel__input--small"
                  :value="localConfig.alarmHigh ?? ''"
                  placeholder="—"
                  @input="updateField('alarmHigh', ($event.target as HTMLInputElement).value ? Number(($event.target as HTMLInputElement).value) : undefined)"
                />
              </div>
            </div>
          </div>

        </div>
      </details>

      <!-- ═══════════════════════════════════════════════════════
           ZONE 3: ERWEITERT — accordion, collapsed by default
           ═══════════════════════════════════════════════════════ -->

      <details v-if="hasZone3" class="config-section">
        <summary class="config-section__header">
          <ChevronRight :size="16" class="config-section__chevron" />
          <span>Erweitert</span>
        </summary>
        <div class="config-section__body">

          <!-- Statistics: Standard deviation -->
          <div class="widget-config-panel__field">
            <label class="widget-config-panel__label-row">
              <span>Standardabweichung anzeigen</span>
              <input
                type="checkbox"
                :checked="localConfig.showStdDev ?? true"
                @change="updateField('showStdDev', ($event.target as HTMLInputElement).checked)"
              />
            </label>
          </div>

          <!-- Statistics: Data quality -->
          <div class="widget-config-panel__field">
            <label class="widget-config-panel__label-row">
              <span>Datenqualitaet anzeigen</span>
              <input
                type="checkbox"
                :checked="localConfig.showQuality ?? false"
                @change="updateField('showQuality', ($event.target as HTMLInputElement).checked)"
              />
            </label>
          </div>

        </div>
      </details>

    </div>
  </SlideOver>
</template>

<style scoped>
.widget-config-panel {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
  padding: var(--space-4);
}

.widget-config-panel__field {
  display: flex;
  flex-direction: column;
  gap: var(--space-1);
}

.widget-config-panel__label {
  font-size: var(--text-xs);
  font-weight: 600;
  color: var(--color-text-secondary);
  text-transform: uppercase;
  letter-spacing: var(--tracking-wide);
}

.widget-config-panel__hint {
  font-weight: 400;
  text-transform: none;
  letter-spacing: normal;
  color: var(--color-text-muted);
}

.widget-config-panel__label-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: var(--text-sm);
  color: var(--color-text-secondary);
}

.widget-config-panel__input {
  padding: var(--space-2);
  background: var(--color-bg-quaternary);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-sm);
  color: var(--color-text-primary);
  font-size: var(--text-sm);
}

.widget-config-panel__input--small {
  width: 100px;
}

.widget-config-panel__select {
  padding: var(--space-2);
  background: var(--color-bg-quaternary);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-sm);
  color: var(--color-text-primary);
  font-size: var(--text-sm);
}

.widget-config-panel__range-row {
  display: flex;
  align-items: center;
  gap: var(--space-2);
}

.widget-config-panel__range-sep {
  color: var(--color-text-muted);
}

.widget-config-panel__chips {
  display: flex;
  gap: var(--space-1);
}

.widget-config-panel__chip {
  padding: var(--space-1) var(--space-2);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-sm);
  background: var(--color-bg-quaternary);
  color: var(--color-text-secondary);
  font-size: var(--text-xs);
  font-weight: 600;
  cursor: pointer;
  transition: all var(--transition-fast);
}

.widget-config-panel__chip:hover {
  border-color: var(--color-accent);
  color: var(--color-text-primary);
}

.widget-config-panel__chip--active {
  background: rgba(59, 130, 246, 0.15);
  border-color: var(--color-accent);
  color: var(--color-accent-bright);
}

.widget-config-panel__color-row {
  display: flex;
  gap: var(--space-2);
}

.widget-config-panel__color-swatch {
  width: 24px;
  height: 24px;
  border-radius: var(--radius-sm);
  border: 2px solid transparent;
  cursor: pointer;
  transition: all var(--transition-fast);
}

.widget-config-panel__color-swatch:hover {
  transform: scale(1.15);
}

.widget-config-panel__color-swatch--active {
  border-color: var(--color-text-primary);
  box-shadow: 0 0 0 2px var(--color-bg-primary);
}

.widget-config-panel__threshold-grid {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
}

.widget-config-panel__threshold-row {
  display: flex;
  align-items: center;
  gap: var(--space-2);
}

.widget-config-panel__threshold-label {
  font-size: var(--text-xs);
  width: 80px;
  flex-shrink: 0;
}

.widget-config-panel__threshold-label--alarm {
  color: var(--color-error);
}

.widget-config-panel__threshold-label--warn {
  color: var(--color-warning);
}

/* ═══ Alert-Config Threshold Sync (P8-A3) ═══ */

.widget-config-panel__sync-btn {
  display: inline-flex;
  align-items: center;
  gap: var(--space-1);
  padding: var(--space-1) var(--space-2);
  background: transparent;
  border: 1px dashed var(--glass-border);
  border-radius: var(--radius-sm);
  color: var(--color-text-secondary);
  font-size: var(--text-xs);
  cursor: pointer;
  transition: all var(--transition-fast);
  min-height: 32px;
}

.widget-config-panel__sync-btn:hover:not(:disabled) {
  border-color: var(--color-accent);
  color: var(--color-accent-bright);
}

.widget-config-panel__sync-btn:disabled {
  opacity: 0.5;
  cursor: wait;
}

.widget-config-panel__sync-msg {
  font-size: var(--text-xs);
  color: var(--color-text-muted);
  font-style: italic;
}

.sync-msg-enter-active {
  transition: opacity 200ms ease;
}

.sync-msg-leave-active {
  transition: opacity 600ms ease;
}

.sync-msg-enter-from,
.sync-msg-leave-to {
  opacity: 0;
}

/* ═══ Accordion (Zone 2 + Zone 3) ═══ */

.config-section {
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-sm);
  overflow: hidden;
}

.config-section__header {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  padding: var(--space-2) var(--space-3);
  background: var(--color-bg-tertiary);
  cursor: pointer;
  font-size: var(--text-sm);
  font-weight: 600;
  color: var(--color-text-secondary);
  user-select: none;
  list-style: none;
  min-height: 44px;
}

.config-section__header::-webkit-details-marker {
  display: none;
}

.config-section__header::marker {
  display: none;
  content: '';
}

.config-section__header:hover {
  color: var(--color-text-primary);
  background: var(--color-bg-quaternary);
}

.config-section__chevron {
  flex-shrink: 0;
  transition: transform 200ms ease;
  color: var(--color-text-muted);
}

details[open] > .config-section__header .config-section__chevron {
  transform: rotate(90deg);
}

.config-section__body {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
  padding: var(--space-3);
  animation: configSlideDown 200ms ease;
}

@keyframes configSlideDown {
  from {
    opacity: 0;
    transform: translateY(-4px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>
