"""
Request-Context for request_id / correlation_id tracking.

Uses contextvars to pass request_id through all layers
without explicit parameter passing.

Two ID types coexist:
- REST requests: UUID (generated by RequestIdMiddleware or received via X-Request-ID header)
- MQTT messages: Human-readable format {esp_id}:{topic_suffix}:{seq}:{timestamp_ms}
"""

import contextvars
import time
from typing import Optional, Union
import uuid

_request_id_ctx: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "request_id", default=None
)


def get_request_id() -> Optional[str]:
    """Return the current request_id (or None)."""
    return _request_id_ctx.get()


def set_request_id(request_id: str) -> contextvars.Token:
    """Set the request_id for the current context.

    Returns token for proper cleanup via clear_request_id(token).
    Backwards-compatible: callers that ignore the return value still work.
    """
    return _request_id_ctx.set(request_id)


def generate_request_id() -> str:
    """Generate a new UUID request_id (for REST requests)."""
    return str(uuid.uuid4())


def generate_mqtt_correlation_id(esp_id: str, topic_suffix: str, seq: Union[int, str, None]) -> str:
    """Generate human-readable correlation ID for MQTT messages.

    Format: {esp_id}:{topic_suffix}:{seq}:{timestamp_ms}
    Example: ESP_12AB34CD:data:142:1708704000000

    Args:
        esp_id: ESP device identifier (from payload or topic)
        topic_suffix: Last segment of MQTT topic (e.g. "data", "heartbeat")
        seq: Sequence number from ESP32 payload (None if absent)

    Returns:
        Correlation ID string for cross-layer tracing
    """
    ts_ms = int(time.time() * 1000)
    seq_part = str(seq) if seq is not None else "no-seq"
    return f"{esp_id}:{topic_suffix}:{seq_part}:{ts_ms}"


def clear_request_id(token: Optional[contextvars.Token] = None) -> None:
    """Clear the request_id from context.

    Args:
        token: If provided, resets ContextVar to the state before set_request_id().
               If None, sets the value to None (backwards-compatible fallback).
    """
    if token is not None:
        _request_id_ctx.reset(token)
    else:
        _request_id_ctx.set(None)
